name: Deploy Heroku

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 pytest
          pip install git+https://github.com/psf/black

      - name: Check code format
        run: black .

      - name: Run tests
        run: make test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Heroku
        run: make heroku
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
